creation_rules:
  # Extra config to only encrypt the actual secret data keys
  - path_regexp: \.(yml|yaml|json|env)$
    key_groups:
      - age:
          - age1je6kjhzuhdjy3fqptpttxjh5k8q46vygzlgtpuq3030c947pc5tqz9dqvr # see key.txt
          - age19j4d6v9j7rx5fs629fu387qz4zmlpsqjexa4s08tkfrrmfdl5cwqjlaupd # humphd
          - age13runq29jhy9kfpaegczrzttykerswh0qprq59msgd754yermtfmsa3hwg2 # tarasglek
