concurrency:
  group: ${{ github.workflow }}

jobs:
  pnpm-publish:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - id: check
        uses: PostHog/check-package-version@v2
      - if: steps.check.outputs.is-new-version == 'true'
        name: Publish if newer
        run: |
          pnpm build
          pnpm publish --no-git-checks --access public
        shell: bash

name: release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
