jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nhedger/setup-sops@v2
      - uses: alessiodionisi/setup-age-action@v1.3.0
      - uses: ./.github/actions/prepare
      - run: pnpm run test:unit

name: Test - Unit

on:
  pull_request: ~
  push:
    branches:
      - main
